// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EfCoreCompiledModels.Models
{
    [DbContext(typeof(BloggingContext))]
    public partial class BloggingContextModel : RuntimeModel
    {
        static BloggingContextModel()
        {
            var model = new BloggingContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static BloggingContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
