// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EfCoreCompiledModels.Models
{
    public partial class BloggingContextModel
    {
        partial void Initialize()
        {
            var blog001 = Blog001EntityType.Create(this);
            var blog002 = Blog002EntityType.Create(this);
            var blog003 = Blog003EntityType.Create(this);
            var blog004 = Blog004EntityType.Create(this);
            var blog005 = Blog005EntityType.Create(this);
            var blog006 = Blog006EntityType.Create(this);
            var blog007 = Blog007EntityType.Create(this);
            var blog008 = Blog008EntityType.Create(this);
            var blog009 = Blog009EntityType.Create(this);
            var blog010 = Blog010EntityType.Create(this);
            var blog011 = Blog011EntityType.Create(this);
            var blog012 = Blog012EntityType.Create(this);
            var blog013 = Blog013EntityType.Create(this);
            var blog014 = Blog014EntityType.Create(this);
            var blog015 = Blog015EntityType.Create(this);
            var blog016 = Blog016EntityType.Create(this);
            var blog017 = Blog017EntityType.Create(this);
            var blog018 = Blog018EntityType.Create(this);
            var blog019 = Blog019EntityType.Create(this);
            var blog020 = Blog020EntityType.Create(this);
            var post001 = Post001EntityType.Create(this);
            var post002 = Post002EntityType.Create(this);
            var post003 = Post003EntityType.Create(this);
            var post004 = Post004EntityType.Create(this);
            var post005 = Post005EntityType.Create(this);
            var post006 = Post006EntityType.Create(this);
            var post007 = Post007EntityType.Create(this);
            var post008 = Post008EntityType.Create(this);
            var post009 = Post009EntityType.Create(this);
            var post010 = Post010EntityType.Create(this);
            var post011 = Post011EntityType.Create(this);
            var post012 = Post012EntityType.Create(this);
            var post013 = Post013EntityType.Create(this);
            var post014 = Post014EntityType.Create(this);
            var post015 = Post015EntityType.Create(this);
            var post016 = Post016EntityType.Create(this);
            var post017 = Post017EntityType.Create(this);
            var post018 = Post018EntityType.Create(this);
            var post019 = Post019EntityType.Create(this);
            var post020 = Post020EntityType.Create(this);

            Post001EntityType.CreateForeignKey1(post001, blog001);
            Post002EntityType.CreateForeignKey1(post002, blog002);
            Post003EntityType.CreateForeignKey1(post003, blog003);
            Post004EntityType.CreateForeignKey1(post004, blog004);
            Post005EntityType.CreateForeignKey1(post005, blog005);
            Post006EntityType.CreateForeignKey1(post006, blog006);
            Post007EntityType.CreateForeignKey1(post007, blog007);
            Post008EntityType.CreateForeignKey1(post008, blog008);
            Post009EntityType.CreateForeignKey1(post009, blog009);
            Post010EntityType.CreateForeignKey1(post010, blog010);
            Post011EntityType.CreateForeignKey1(post011, blog011);
            Post012EntityType.CreateForeignKey1(post012, blog012);
            Post013EntityType.CreateForeignKey1(post013, blog013);
            Post014EntityType.CreateForeignKey1(post014, blog014);
            Post015EntityType.CreateForeignKey1(post015, blog015);
            Post016EntityType.CreateForeignKey1(post016, blog016);
            Post017EntityType.CreateForeignKey1(post017, blog017);
            Post018EntityType.CreateForeignKey1(post018, blog018);
            Post019EntityType.CreateForeignKey1(post019, blog019);
            Post020EntityType.CreateForeignKey1(post020, blog020);

            Blog001EntityType.CreateAnnotations(blog001);
            Blog002EntityType.CreateAnnotations(blog002);
            Blog003EntityType.CreateAnnotations(blog003);
            Blog004EntityType.CreateAnnotations(blog004);
            Blog005EntityType.CreateAnnotations(blog005);
            Blog006EntityType.CreateAnnotations(blog006);
            Blog007EntityType.CreateAnnotations(blog007);
            Blog008EntityType.CreateAnnotations(blog008);
            Blog009EntityType.CreateAnnotations(blog009);
            Blog010EntityType.CreateAnnotations(blog010);
            Blog011EntityType.CreateAnnotations(blog011);
            Blog012EntityType.CreateAnnotations(blog012);
            Blog013EntityType.CreateAnnotations(blog013);
            Blog014EntityType.CreateAnnotations(blog014);
            Blog015EntityType.CreateAnnotations(blog015);
            Blog016EntityType.CreateAnnotations(blog016);
            Blog017EntityType.CreateAnnotations(blog017);
            Blog018EntityType.CreateAnnotations(blog018);
            Blog019EntityType.CreateAnnotations(blog019);
            Blog020EntityType.CreateAnnotations(blog020);
            Post001EntityType.CreateAnnotations(post001);
            Post002EntityType.CreateAnnotations(post002);
            Post003EntityType.CreateAnnotations(post003);
            Post004EntityType.CreateAnnotations(post004);
            Post005EntityType.CreateAnnotations(post005);
            Post006EntityType.CreateAnnotations(post006);
            Post007EntityType.CreateAnnotations(post007);
            Post008EntityType.CreateAnnotations(post008);
            Post009EntityType.CreateAnnotations(post009);
            Post010EntityType.CreateAnnotations(post010);
            Post011EntityType.CreateAnnotations(post011);
            Post012EntityType.CreateAnnotations(post012);
            Post013EntityType.CreateAnnotations(post013);
            Post014EntityType.CreateAnnotations(post014);
            Post015EntityType.CreateAnnotations(post015);
            Post016EntityType.CreateAnnotations(post016);
            Post017EntityType.CreateAnnotations(post017);
            Post018EntityType.CreateAnnotations(post018);
            Post019EntityType.CreateAnnotations(post019);
            Post020EntityType.CreateAnnotations(post020);

            AddAnnotation("ProductVersion", "7.0.11");
        }
    }
}
